### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by rsnape** [IESD/MECS#4]
Raising this so we don't forget.  Just did a full clean install exactly according to instructions.  Two "buglets" noted.

1.  You have to do the reboot manually at the end of the script - we should add it either to the script, or to the instructions.
2. If the ADC is not in use, we get an Exception that is not caught.  Specifically:
`2021-07-05 19:37:52,810 ERROR [MECS.cli][MainThread] [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/MECS-0.2.5-py3.7.egg/MECS/cli.py", line 78, in get_board
    return MECSBoard(bit_rate, input_impedance, CALIBRATION)
  File "/usr/local/lib/python3.7/dist-packages/MECS-0.2.5-py3.7.egg/MECS/data_acquisition/__init__.py", line 102, in __init__
    self.adc = ADCPi(bus, rate=bit_rate)
  File "/usr/local/lib/python3.7/dist-packages/MECS-0.2.5-py3.7.egg/MECS/data_acquisition/ADCPi/ABE_ADCPi.py", line 105, in __init__
    self.set_bit_rate(rate)
  File "/usr/local/lib/python3.7/dist-packages/MECS-0.2.5-py3.7.egg/MECS/data_acquisition/ADCPi/ABE_ADCPi.py", line 260, in set_bit_rate
    self._bus.write_byte(self.__address, self.__config1)
OSError: [Errno 121] Remote I/O error`

**Comment by ggstuart** [comment]
Can this be closed?
