### ISSUE TITLE
re-run of `mecs-init` failed

### ISSUE THREAD

**Issue by rsnape** [IESD/MECS#6]
Trying to relabel a system, had a failure of the mecs-init script - output below

On other things, but looks like the config parser is trying to read the label as an int.  Was it originally going to be a serial number?

```
me@raspberrypi:~/MECS $ mecs-init
2021-09-02 09:45:29,791 INFO  [MECS.config][MainThread] Configuration loaded from /home/pi/MECS.ini
2021-09-02 09:45:29,835 INFO  [MECS.cli][MainThread] MECS v0.2.5 initialising
Traceback (most recent call last):
  File "/usr/local/bin/mecs-init", line 11, in <module>
    load_entry_point('MECS', 'console_scripts', 'mecs-init')()
  File "/home/pi/MECS/MECS/cli.py", line 127, in init
    initialise_unit_id(args.conf, conf)
  File "/home/pi/MECS/MECS/config.py", line 32, in initialise_unit_id
    existing_unit_id = conf.getint('MECS', 'unit_id', fallback=False)
  File "/usr/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: 'PiZeroLabTest2'
me@raspberrypi:~/MECS $ sudo mecs-init
2021-09-02 09:45:44,640 INFO  [MECS.config][MainThread] Configuration loaded from /home/pi/MECS.ini
2021-09-02 09:45:44,685 INFO  [MECS.cli][MainThread] MECS v0.2.5 initialising
Traceback (most recent call last):
  File "/usr/local/bin/mecs-init", line 11, in <module>
    load_entry_point('MECS', 'console_scripts', 'mecs-init')()
  File "/home/pi/MECS/MECS/cli.py", line 127, in init
    initialise_unit_id(args.conf, conf)
  File "/home/pi/MECS/MECS/config.py", line 32, in initialise_unit_id
    existing_unit_id = conf.getint('MECS', 'unit_id', fallback=False)
  File "/usr/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: 'PiZeroLabTest2'
```

**Comment by ggstuart** [comment]
Should be fixed now. I initially assumed integers.
